# Generated by Django 3.0.6 on 2020-07-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200730_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='fullfill_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
