# Generated by Django 3.0.6 on 2020-07-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_campaign_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
