# Generated by Django 3.0.6 on 2020-07-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20200730_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
