# Generated by Django 3.0.6 on 2020-08-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20200730_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='visitor',
            field=models.BooleanField(default=False),
        ),
    ]
